# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtAYekfNCo6LFKsldPWeZeqJfRMh7F6C
"""

import streamlit as st
import pandas as pd
import os
import matplotlib.pyplot as plt

# Define the base directory for district data
BASE_DIR = "path_to_your_github_repo"  # Replace with your GitHub folder path

# Function to load data from a selected file
def load_data(file_path):
    data = pd.read_csv(file_path, skiprows=1)
    data.columns = ["Timestamp", "Discharge (cfs)", "Gage Height (ft)"]
    data['Timestamp'] = pd.to_datetime(data['Timestamp'], errors='coerce')
    return data.dropna(subset=['Timestamp'])

# Streamlit UI
st.title("New Mexico Stream Data Dashboard")

# Select district folder
districts = [f for f in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR, f))]
selected_district = st.selectbox("Select District", districts)

# Select file within district
district_path = os.path.join(BASE_DIR, selected_district)
files = [f for f in os.listdir(district_path) if f.endswith('.csv')]
selected_file = st.selectbox("Select Stream File", files)

# Parse stream name from file name
stream_name = os.path.splitext(selected_file)[0]
st.subheader(f"Stream: {stream_name}")

# Load and display data
file_path = os.path.join(district_path, selected_file)
data = load_data(file_path)

# Select data to plot
plot_options = st.multiselect("Select Data to Plot", ["Discharge (cfs)", "Gage Height (ft)"], default=["Discharge (cfs)"])

if plot_options:
    fig, ax = plt.subplots(figsize=(10, 6))
    for option in plot_options:
        ax.plot(data["Timestamp"], data[option], label=option)
    ax.set_title(f"{stream_name} Data")
    ax.set_xlabel("Timestamp")
    ax.set_ylabel("Value")
    ax.legend()
    st.pyplot(fig)